<?php
/**
 * Temporary Doctors Data for Development
 * Enhanced doctor profiles for Find Doctors and Booking functionality
 */

function getTempDoctorsData() {
    return [
        [
            'id' => 1,
            'name' => 'Dr. Sarah Johnson',
            'specialty' => 'Cardiology',
            'subspecialty' => 'Interventional Cardiology',
            'experience' => 15,
            'rating' => 4.9,
            'reviews' => 234,
            'consultation_fee' => 250.00,
            'education' => 'MD - Harvard Medical School',
            'hospital' => 'Apollo Hospital',
            'location' => 'Colombo 07',
            'phone' => '+1 (555) 123-4567',
            'email' => 'dr.johnson@cityhospital.com',
            'languages' => ['English', 'Spanish'],
            'bio' => 'Dr. Johnson is a board-certified cardiologist with over 15 years of experience in treating complex heart conditions. She specializes in interventional procedures and has performed over 2,000 cardiac catheterizations.',
            'conditions' => ['Heart Disease', 'Hypertension', 'Arrhythmia', 'Heart Failure', 'Coronary Artery Disease', 'Chest Pain'],
            'nextAvailable' => 'Today 2:00 PM',
            'consultationType' => ['In-person', 'Video Call'],
            'available' => true,
            'patients_treated' => 2500,
            'certifications' => ['Board Certified Cardiologist', 'Advanced Cardiac Life Support'],
            'image' => 'doctor1.jpg'
        ],
        [
            'id' => 2,
            'name' => 'Dr. Michael Chen',
            'specialty' => 'Orthopedic Surgery',
            'subspecialty' => 'Sports Medicine',
            'experience' => 12,
            'rating' => 4.8,
            'reviews' => 189,
            'consultation_fee' => 280.00,
            'education' => 'MD - Johns Hopkins University',
            'hospital' => 'Asiri Hospital',
            'location' => 'Colombo 05',
            'phone' => '+1 (555) 234-5678',
            'email' => 'm.chen@sportsmedicine.com',
            'languages' => ['English', 'Mandarin'],
            'bio' => 'Dr. Chen is a renowned orthopedic surgeon specializing in sports-related injuries. He has worked with professional athletes and is known for his minimally invasive surgical techniques.',
            'conditions' => ['Sports Injuries', 'Joint Pain', 'Fractures', 'Arthritis', 'ACL Reconstruction', 'Knee Surgery'],
            'nextAvailable' => 'Tomorrow 9:00 AM',
            'consultationType' => ['In-person'],
            'available' => true,
            'patients_treated' => 1800,
            'certifications' => ['Board Certified Orthopedic Surgeon', 'Sports Medicine Specialist'],
            'image' => 'doctor2.jpg'
        ],
        [
            'id' => 3,
            'name' => 'Dr. Emily Rodriguez',
            'specialty' => 'Pediatrics',
            'subspecialty' => 'Developmental Pediatrics',
            'experience' => 8,
            'rating' => 4.7,
            'reviews' => 156,
            'consultation_fee' => 180.00,
            'education' => 'MD - Stanford Medical School',
            'hospital' => 'Nawaloka Hospital',
            'location' => 'Colombo 02',
            'phone' => '+1 (555) 345-6789',
            'email' => 'e.rodriguez@childrenscenter.com',
            'languages' => ['English', 'Spanish', 'Portuguese'],
            'bio' => 'Dr. Rodriguez is passionate about child development and provides comprehensive pediatric care. She has special expertise in developmental delays and behavioral issues in children.',
            'conditions' => ['Child Development', 'Vaccines', 'Common Childhood Illnesses', 'Growth Disorders', 'ADHD', 'Autism Spectrum'],
            'nextAvailable' => 'Today 4:00 PM',
            'consultationType' => ['In-person', 'Video Call'],
            'available' => true,
            'patients_treated' => 1200,
            'certifications' => ['Board Certified Pediatrician', 'Developmental Behavioral Pediatrics'],
            'image' => 'doctor3.jpg'
        ],
        [
            'id' => 4,
            'name' => 'Dr. David Wilson',
            'specialty' => 'Dermatology',
            'subspecialty' => 'Cosmetic Dermatology',
            'experience' => 10,
            'rating' => 4.6,
            'reviews' => 142,
            'consultation_fee' => 220.00,
            'education' => 'MD - UCLA Medical School',
            'hospital' => 'Durdans Hospital',
            'location' => 'Colombo 03',
            'phone' => '+1 (555) 456-7890',
            'email' => 'd.wilson@skincare.com',
            'languages' => ['English'],
            'bio' => 'Dr. Wilson combines medical and cosmetic dermatology to provide comprehensive skin care. He is known for his expertise in skin cancer detection and advanced cosmetic procedures.',
            'conditions' => ['Acne', 'Skin Cancer', 'Eczema', 'Cosmetic Procedures', 'Psoriasis', 'Moles and Lesions'],
            'nextAvailable' => 'Monday 10:00 AM',
            'consultationType' => ['In-person', 'Video Call'],
            'available' => true,
            'patients_treated' => 950,
            'certifications' => ['Board Certified Dermatologist', 'Cosmetic Surgery Certified'],
            'image' => 'doctor4.jpg'
        ],
        [
            'id' => 5,
            'name' => 'Dr. Lisa Anderson',
            'specialty' => 'Neurology',
            'subspecialty' => 'Movement Disorders',
            'experience' => 14,
            'rating' => 4.9,
            'reviews' => 198,
            'consultation_fee' => 320.00,
            'education' => 'MD - Mayo Clinic Medical School',
            'hospital' => 'Lanka Hospital',
            'location' => 'Colombo 05',
            'phone' => '+1 (555) 567-8901',
            'email' => 'l.anderson@neuroinstitute.com',
            'languages' => ['English', 'French'],
            'bio' => 'Dr. Anderson is a leading neurologist specializing in movement disorders. She has extensive research experience and is involved in clinical trials for new neurological treatments.',
            'conditions' => ['Parkinson\'s Disease', 'Epilepsy', 'Migraines', 'Multiple Sclerosis', 'Stroke', 'Tremors'],
            'nextAvailable' => 'Today 1:00 PM',
            'consultationType' => ['In-person', 'Video Call'],
            'available' => true,
            'patients_treated' => 1600,
            'certifications' => ['Board Certified Neurologist', 'Movement Disorders Specialist'],
            'image' => 'doctor5.jpg'
        ],
        [
            'id' => 6,
            'name' => 'Dr. James Thompson',
            'specialty' => 'General Surgery',
            'subspecialty' => 'Minimally Invasive Surgery',
            'experience' => 18,
            'rating' => 4.8,
            'reviews' => 267,
            'consultation_fee' => 350.00,
            'education' => 'MD - Cleveland Clinic Medical School',
            'hospital' => 'National Hospital of Sri Lanka',
            'location' => 'Colombo 10',
            'phone' => '+1 (555) 678-9012',
            'email' => 'j.thompson@metrosurgical.com',
            'languages' => ['English'],
            'bio' => 'Dr. Thompson is an experienced general surgeon with expertise in minimally invasive techniques. He has pioneered several laparoscopic procedures and has a excellent track record in complex surgeries.',
            'conditions' => ['Gallbladder Surgery', 'Hernia Repair', 'Appendectomy', 'Colon Surgery', 'Laparoscopic Surgery', 'Emergency Surgery'],
            'nextAvailable' => 'Tuesday 8:00 AM',
            'consultationType' => ['In-person'],
            'available' => true,
            'patients_treated' => 3200,
            'certifications' => ['Board Certified General Surgeon', 'Laparoscopic Surgery Specialist'],
            'image' => 'doctor6.jpg'
        ],
        [
            'id' => 7,
            'name' => 'Dr. Priya Perera',
            'specialty' => 'Internal Medicine',
            'subspecialty' => 'Endocrinology',
            'experience' => 11,
            'rating' => 4.7,
            'reviews' => 167,
            'consultation_fee' => 200.00,
            'education' => 'MBBS - University of Colombo',
            'hospital' => 'Asiri Central Hospital',
            'location' => 'Colombo 01',
            'phone' => '+94 11 123-4567',
            'email' => 'p.perera@asiricentral.com',
            'languages' => ['English', 'Sinhala', 'Tamil'],
            'bio' => 'Dr. Perera specializes in diabetes management and thyroid disorders. She has extensive experience in managing complex endocrine conditions.',
            'conditions' => ['Diabetes', 'Thyroid Disorders', 'Hypertension', 'Obesity', 'Hormonal Imbalances'],
            'nextAvailable' => 'Today 3:00 PM',
            'consultationType' => ['In-person', 'Video Call'],
            'available' => true,
            'patients_treated' => 1400,
            'certifications' => ['Board Certified Endocrinologist', 'Diabetes Specialist'],
            'image' => 'doctor7.jpg'
        ],
        [
            'id' => 8,
            'name' => 'Dr. Rajesh Fernando',
            'specialty' => 'Gastroenterology',
            'subspecialty' => 'Hepatology',
            'experience' => 13,
            'rating' => 4.8,
            'reviews' => 203,
            'consultation_fee' => 275.00,
            'education' => 'MD - University of Kelaniya',
            'hospital' => 'Teaching Hospital Kandy',
            'location' => 'Kandy',
            'phone' => '+94 81 234-5678',
            'email' => 'r.fernando@teachingkandy.ac.lk',
            'languages' => ['English', 'Sinhala'],
            'bio' => 'Dr. Fernando is a renowned gastroenterologist with expertise in liver diseases and digestive disorders.',
            'conditions' => ['Liver Disease', 'Digestive Disorders', 'Hepatitis', 'Inflammatory Bowel Disease', 'Endoscopy'],
            'nextAvailable' => 'Tomorrow 11:00 AM',
            'consultationType' => ['In-person'],
            'available' => true,
            'patients_treated' => 1850,
            'certifications' => ['Board Certified Gastroenterologist', 'Hepatology Specialist'],
            'image' => 'doctor8.jpg'
        ],
        [
            'id' => 9,
            'name' => 'Dr. Samanthi Silva',
            'specialty' => 'Obstetrics & Gynecology',
            'subspecialty' => 'Maternal-Fetal Medicine',
            'experience' => 9,
            'rating' => 4.9,
            'reviews' => 145,
            'consultation_fee' => 195.00,
            'education' => 'MBBS - University of Sri Jayewardenepura',
            'hospital' => 'Karapitiya Teaching Hospital',
            'location' => 'Galle',
            'phone' => '+94 91 345-6789',
            'email' => 's.silva@karapitiya.ac.lk',
            'languages' => ['English', 'Sinhala'],
            'bio' => 'Dr. Silva provides comprehensive women\'s healthcare with special focus on high-risk pregnancies and maternal care.',
            'conditions' => ['Pregnancy Care', 'Gynecological Disorders', 'Infertility', 'Prenatal Care', 'Women\'s Health'],
            'nextAvailable' => 'Today 2:30 PM',
            'consultationType' => ['In-person', 'Video Call'],
            'available' => true,
            'patients_treated' => 980,
            'certifications' => ['Board Certified OB/GYN', 'Maternal-Fetal Medicine Specialist'],
            'image' => 'doctor9.jpg'
        ],
        [
            'id' => 10,
            'name' => 'Dr. Nuwan Wickramasinghe',
            'specialty' => 'Urology',
            'subspecialty' => 'Minimally Invasive Surgery',
            'experience' => 12,
            'rating' => 4.6,
            'reviews' => 134,
            'consultation_fee' => 260.00,
            'education' => 'MS - Postgraduate Institute of Medicine',
            'hospital' => 'Hemas Hospital Wattala',
            'location' => 'Wattala',
            'phone' => '+94 11 456-7890',
            'email' => 'n.wickramasinghe@hemas.com',
            'languages' => ['English', 'Sinhala'],
            'bio' => 'Dr. Wickramasinghe specializes in urological conditions with expertise in laparoscopic and robotic surgery.',
            'conditions' => ['Kidney Stones', 'Prostate Disorders', 'Urinary Tract Infections', 'Male Infertility', 'Bladder Issues'],
            'nextAvailable' => 'Monday 9:00 AM',
            'consultationType' => ['In-person'],
            'available' => true,
            'patients_treated' => 1150,
            'certifications' => ['Board Certified Urologist', 'Laparoscopic Surgery Specialist'],
            'image' => 'doctor10.jpg'
        ],
        [
            'id' => 11,
            'name' => 'Dr. Chamara Jayawardena',
            'specialty' => 'Emergency Medicine',
            'subspecialty' => 'Trauma Care',
            'experience' => 7,
            'rating' => 4.5,
            'reviews' => 98,
            'consultation_fee' => 150.00,
            'education' => 'MBBS - University of Ruhuna',
            'hospital' => 'Base Hospital Negombo',
            'location' => 'Negombo',
            'phone' => '+94 31 567-8901',
            'email' => 'c.jayawardena@negombohospital.gov.lk',
            'languages' => ['English', 'Sinhala'],
            'bio' => 'Dr. Jayawardena provides emergency medical care with expertise in trauma management and critical care.',
            'conditions' => ['Emergency Care', 'Trauma Management', 'Critical Care', 'Accident Injuries', 'Acute Medical Conditions'],
            'nextAvailable' => 'Available 24/7',
            'consultationType' => ['In-person'],
            'available' => true,
            'patients_treated' => 750,
            'certifications' => ['Emergency Medicine Certified', 'Advanced Trauma Life Support'],
            'image' => 'doctor11.jpg'
        ],
        [
            'id' => 12,
            'name' => 'Dr. Anushka Mendis',
            'specialty' => 'Plastic Surgery',
            'subspecialty' => 'Reconstructive Surgery',
            'experience' => 10,
            'rating' => 4.7,
            'reviews' => 122,
            'consultation_fee' => 300.00,
            'education' => 'MS - Royal College of Surgeons',
            'hospital' => 'Asiri Surgical Hospital',
            'location' => 'Colombo 06',
            'phone' => '+94 11 678-9012',
            'email' => 'a.mendis@asirisurgical.com',
            'languages' => ['English', 'Sinhala'],
            'bio' => 'Dr. Mendis specializes in reconstructive and aesthetic plastic surgery with expertise in complex reconstructive procedures.',
            'conditions' => ['Reconstructive Surgery', 'Cosmetic Surgery', 'Burn Treatment', 'Hand Surgery', 'Facial Reconstruction'],
            'nextAvailable' => 'Tuesday 10:00 AM',
            'consultationType' => ['In-person'],
            'available' => true,
            'patients_treated' => 890,
            'certifications' => ['Board Certified Plastic Surgeon', 'Reconstructive Surgery Specialist'],
            'image' => 'doctor12.jpg'
        ]
    ];
}

function getAvailableTimeSlots($doctorId, $date) {
    // Generate realistic time slots based on doctor and date
    $morningSlots = ['09:00', '09:30', '10:00', '10:30', '11:00', '11:30'];
    $afternoonSlots = ['14:00', '14:30', '15:00', '15:30', '16:00', '16:30'];
    $eveningSlots = ['17:00', '17:30', '18:00', '18:30'];
    
    // Simulate some slots being booked
    $bookedSlots = ['10:00', '15:00', '17:30'];
    
    return [
        'morning' => array_diff($morningSlots, $bookedSlots),
        'afternoon' => array_diff($afternoonSlots, $bookedSlots),
        'evening' => array_diff($eveningSlots, $bookedSlots)
    ];
}
?>
